### ISSUE TITLE
Binding correction and page footers

### ISSUE THREAD

**Issue by bsteinb** [OpenMP/Examples#27]
There seems to be an issue with the position of the binding correction and page footers (page number etc.) in both the OpenMP Specification and Examples document. The front matter (table of contents) in both books ends on an odd page, with binding correction on the left and page footers on the right. This page is immediately followed by the first page of the body matter (Introduction) which also has the binding correction on the left and page footers on the right. When producing bound printed copies of the books this will result in the line numbers and page footers in the body matter appearing next to and very close to the binding. We have worked around this issue by inserting a blank page between front matter and body matter. Could this blank page be included in the official versions of the documents?

**Comment by HenryJin** [comment]
This issue can be closed now since both spec (5.0+) and examples (5.1+) documents have implemented the proper page numbers.
